apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: voteapp
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: voteapp
    name: postgres
