apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voteapp
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: voteapp
    name: redis
