apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote
    app: voteapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voteapp
    name: vote
