apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote
    app: voteapp
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 80
  selector:
    app: voteapp
    name: vote
